### ISSUE TITLE
No .apk in repo?

### ISSUE THREAD

**Issue by jowe2** [razzo04/rhasspy-mobile-app#1]
I'd love to try your app. As I don't want to compile, I was looking for the apk. But I couldn't find one...

**Comment by razzo04** [comment]
Every time I release a new version, I attach the .apk compiled.
https://github.com/razzo04/rhasspy-mobile-app/releases/tag/v1.5.0

**Comment by jowe2** [comment]
> Every time I release a new version, I attach the .apk compiled.
> https://github.com/razzo04/rhasspy-mobile-app/releases/tag/v1.5.0

Great, thank you!
