### ISSUE TITLE
unable to make APK

### ISSUE THREAD

**Issue by miit86** [razzo04/rhasspy-mobile-app#5]
Hi, im unable to build the APK.
where can I find the APK?

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.1\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

**Comment by razzo04** [comment]
The apk can be found in the [release](https://github.com/razzo04/rhasspy-mobile-app/releases/tag/v1.7.0). Flutter sometimes complains that before compiling the release it is not compiled in profile or debugging mode so you can try to compile with the flags "--debug" or "--profile".
