### ISSUE TITLE
Home Assistant Handle not working

### ISSUE THREAD

**Issue by kaykoch** [razzo04/rhasspy-mobile-app#9]
I tried the App, and as long as nodered handled the intents averything works perfekt.
Now, I changed to Hassio. Rhasspy Integration works but even with checkbox "Handle?" checked, there is no reaction.
I can see the intent on the rhasspy masterr, Hassio does not react  and the app says:

```
no one managed the intent:
<intentName>
```

Did I missunderstood the checkbox?

sincerly
Kay Koch
![Screenshot_20210306-183450](https://user-images.githubusercontent.com/49059258/110215606-fed76080-7eaa-11eb-81be-ee7fe9b401fc.png)

![Screenshot_20210306-183460](https://user-images.githubusercontent.com/49059258/110215693-6392bb00-7eab-11eb-8fb2-568436a5fad4.png)

**Comment by kaykoch** [comment]
Solved.
I updated to 1.17

I tried :
`Auto-Setup`
After first time, I got an answer, which means something like:
`configuaration from rhasspy and app are different`
This was right. I used another mqtt user in rhasspy master. I changed it to the same as in the app and everythings works now

**Comment by razzo04** [comment]
I’m glad it works, maybe in the next versions, I’ll put a notification to notify of new versions of the app.
